TwitterAccounts = [
    "mizuno_takaaki",
    "yukihiro_matz",
    "rob_pike",
    "dhh",
    "naoya_ito",
    "takoratta",
    "masuidrive",
    "yugui",
    "mizchi",
    "Jxck_",
    "t_wada",
    "miyagawa",
    "fshin2000",
    "fujiwara",
    "mattn_jp",
    "songmu",
]
